### ISSUE TITLE
TypeError: this.THREE.GLTFLoader is not a constructor

### ISSUE THREAD

**Issue by metipton** [johh/three-gltf-loader#1]
I'm currently having issues getting the GLTF loader to work properly in my my react app with plain threejs.   Here are a few code snippets that should help.  I've used every permutation I can think of with using "this" and not using "this" but havent been able to get it to work. Any thoughts would be appreciated!

    import * as GLTFLoader from 'three-gltf-loader';
    GLTFLoader(THREE);

     this.THREE = THREE;
     var ObjLoader = new this.THREE.OBJLoader( );
     var GltfLoader = new this.THREE.GLTFLoader();
     if(this.state.current.Race === null){
         GltfLoader.load( Zoid, function ( object ) {
             scene.add(object);
             object.position.y = -1;

         });
     } else {
         console.log("Not loaded");
     }

**Comment by johh** [comment]
Hey there,

this module imports `three` as a peer dependency internally, so there's no need for `GLTFLoader(THREE);`.
A limitation of this is that `THREE.GLTFLoader` remains undefined, however, the constructor is directly exported by `three-gltf-loader`.

I've modified your example – the following should work: 

```javascript
import * as THREE from 'three';
import GLTFLoader from 'three-gltf-loader';

const loader = new GLTFLoader();
if( this.state.current.Race === null ) {
  loader.load(
    'path/to/your/model.gltf',
    ( gltf ) => {
      yourScene.add( gltf.scene );
    },
  )
} else {
  console.log( 'Not loaded' );
}
```

**Comment by metipton** [comment]
Thanks for getting back to me.  The scene now loads but the following exception is thrown when attempting to load the model.


 index.js:1895 Uncaught (in promise) RangeError: Invalid typed array length: 22704
    at new Uint16Array (<anonymous>)
    at index.js:1895

Is this most likely an issue with my .glltf file?  I'm using the most recent Khronos importer exporter from blender and I'm only exporting the selected model.  Additionally, the GLTF validator says that the format was valid.  I am however getting the following error in the validation message:

        "messages": [
            {
                "code": "MESH_PRIMITIVE_UNUSED_TEXCOORD",
                "message": "Material does not use texture coordinates sets with indices (0).",
                "severity": 2,
                "pointer": "/meshes/0/primitives/0/material"
            }
        ],

**Comment by johh** [comment]
Yes, it seems to be related to your .gltf file. I'd try importing a [known-good model](https://github.com/mrdoob/three.js/tree/master/examples/models/gltf/DamagedHelmet) just to be sure.
