### ISSUE TITLE
geometry.setAttribute is not a function

### ISSUE THREAD

**Issue by beTyler** [johh/three-gltf-loader#10]
GLTFLoaderTest.vue?2dc1:36 An error happened TypeError: geometry.setAttribute is not a function

**Comment by beTyler** [comment]
Hello, may I ask if I used it in the wrong way? Why did I report this mistake

**Comment by beTyler** [comment]
function addPrimitiveAttributes( geometry, primitiveDef, parser ) {

		var attributes = primitiveDef.attributes;

		var pending = [];

		function assignAttributeAccessor( accessorIndex, attributeName ) {

			return parser.getDependency( 'accessor', accessorIndex )
				.then( function ( accessor ) {

					geometry.setAttribute( attributeName, accessor );

				} );

		}

**Comment by johh** [comment]
Hey there, sorry for the late reply! 
This package is just a wrapper around `GLTFLoader` and no longer maintained, sorry for the confusion!
The best place to ask Three.js related questions is the forum: [https://discourse.threejs.org/](https://discourse.threejs.org/ )
