### ISSUE TITLE
Type definition files for Typescript

### ISSUE THREAD

**Issue by lochbrunner** [johh/three-gltf-loader#2]
Hi, I was wondering if you are planing to create some definition files in order to make the usage of this library more comfortable in Typescript projects.

Are PRs for that welcome?

**Comment by johh** [comment]
Hey! Yes, I was planning to add them at some point in the future, however, it is currently not a priority.

> Are PRs for that welcome?

Absolutely! I'll get it merged and published asap.

**Comment by johh** [comment]
Ok, closing for now. You can start a PR once you're ready! 👍

**Comment by johh** [comment]
TypeScript type definitions are now included (starting with v1.99.1), courtesy of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/three-gltfloader.d.ts).
