### ISSUE TITLE
GTLF Loader Issue

### ISSUE THREAD

**Issue by russianbadass** [johh/three-gltf-loader#7]
Can someone help me? My GLTFloader isn't loading my model idk what to do. 

<!DOCTYPE html>
<html>
  <head>
    <meta charset=UTF-8 />
    <link rel="stylesheet" type="text/css" href="styles.css" />
  </head>
  <body>
      
    <script src="three.min.js"></script>
    <script src="GLTFLoader.js"></script>
    <script src="OrbitControls.js"></script>
    <script> import * as THREE from 'three';
      import GLTFLoader from 'three-gltf-loader';
    </script>
   
                
      
    <script>
        var scene = new THREE.Scene();
        scene.background = new THREE.Color()
        
   

        
    
        
        var camera = new THREE.PerspectiveCamera(40,window.innderWidth/window.innerHeight,1,5000);
        camera.position.set( -1.5, 1.5, 6.5 );
        
        
            
        var light = new THREE.AmbientLight (0x404040,100);
        scene.add(light);
        
        var renderer = new THREE.WebGLRenderer({antialias:true});
        renderer.setSize(window.innerWidth,window.innerHeight);
        document.body.appendChild(renderer.domElement);
        
    
       /* const loader = new THREE.GLTFLoader();
        
        const url = 'scene.gltf'
        
        const onLoad = ( gltf ) => {
        
        console.log( gltf );
        
        
        
        };
        
        loader.load (url, onLoad );*/
        

   

        
        const loader = new GLTFLoader();
if( this.state.current.Race === null ) {
  loader.load(
    'scene.gltf',
    ( gltf ) => {
      yourScene.add( gltf.scene );
    },
  )
} else {
  console.log( 'Not loaded' );
}
    
   

        
        
 
    </script>
  </body>
</html>

**Comment by johh** [comment]
Hey there,
`three-gltf-loader` is intended to be used with a module system and not in the browser directly.
three.js provides a browser compatible loader [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js).

From your code, I'm guessing that you're new to JS. If you can provide a repository with your project, I'd be happy to help you get things running.
