### ISSUE TITLE
Please archive this repository and deprecate the npm package.

### ISSUE THREAD

**Issue by Mugen87** [johh/three-gltf-loader#9]
There are still too many user which include the `npm` package in their project instead of using the `GLTFLoader` module from the official repository. This problem causes noticeable support efforts e.g.:

https://discourse.threejs.org/t/3d-model-from-blender-and-use-shape-keys/11851

Archiving the project and deprecate the npm package would help to mitigate this issue:

https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by johh** [comment]
Right, I'll deprecate the package to make it more clear.

**Comment by Mugen87** [comment]
That's great! Thanks!

**Comment by Mugen87** [comment]
Let's keep this open until the package is actually deprecated.

**Comment by johh** [comment]
Done.
